version: "3.9"
services:
  web:
    build: .
    ports:
      - "8001:8001"
    command: daphne config.asgi:application --port=8001 --bind 0.0.0.0 -v2
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - ./.env.dev
  
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:

